services:
  web:
    build:
      context: .
    container_name: {{ cookiecutter.project_slug }}_web
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "{{ cookiecutter.project_slug }}.settings"
      CLOUDRON_POSTGRESQL_DATABASE: "{{ cookiecutter.project_slug }}_db"
      CLOUDRON_POSTGRESQL_USERNAME: "{{ cookiecutter.project_slug }}_user"
      CLOUDRON_POSTGRESQL_PASSWORD: "{{ cookiecutter.project_slug }}_password"
      CLOUDRON_POSTGRESQL_HOST: "postgres"
      CLOUDRON_POSTGRESQL_PORT: "5432"
      CLOUDRON_REDIS_HOST: "redis"
      CLOUDRON_REDIS_PORT: "6379"
      CLOUDRON_REDIS_PASSWORD: ""
      CLOUDRON_OIDC_CLIENT_ID: ""
      CLOUDRON_OIDC_CLIENT_SECRET: ""
      DJANGO_SECURE_SSL_REDIRECT: "False"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_CSRF_TRUSTED_ORIGINS: "*"
      DJANGO_SESSION_COOKIE_SECURE: "False"
      DJANGO_CSRF_COOKIE_SECURE: "False"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app/code

  postgres:
    image: postgres:13
    container_name: {{ cookiecutter.project_slug }}_postgres
    environment:
      POSTGRES_DB: "{{ cookiecutter.project_slug }}_db"
      POSTGRES_USER: "{{ cookiecutter.project_slug }}_user"
      POSTGRES_PASSWORD: "{{ cookiecutter.project_slug }}_password"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: {{ cookiecutter.project_slug }}_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
